<!DOCTYPE html>
<html>
  <head>
    <meta name="pypi:repository-version" content="1.0">
    <title>Links for odoo-addon-base-exception</title>
  </head>
  <body>
    <h1>Links for odoo-addon-base-exception</h1>
    <a href="https://files.pythonhosted.org/packages/47/b9/4c4c33881aa9439fff69032ac7e3cd29c803e2768822369768093ecf6c5d/odoo_addon_base_exception-15.0.1.0.0.2-py3-none-any.whl#sha256=ebf9e3312837506d22ca991c8c94c8b5c0c56b7a16408db546a6afb122db0f18" data-requires-python="&gt;=3.8" >odoo_addon_base_exception-15.0.1.0.0.2-py3-none-any.whl</a><br />
    <a href="https://files.pythonhosted.org/packages/f9/62/d55e34d0689e62be7f3c5705e45a4b86eaff72d3f0834f8fbff25e087fd8/odoo_addon_base_exception-15.0.1.0.1-py3-none-any.whl#sha256=5b9c6a828a0bc3671f45ccd96e5c4edaf2d1e396517240b3b40e190c3311a861" data-requires-python="&gt;=3.8" >odoo_addon_base_exception-15.0.1.0.1-py3-none-any.whl</a><br />
    </body>
</html>
<!--SERIAL 14446138-->